# Generated by Django 2.1.1 on 2018-09-14 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_category_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
    ]
