# Generated by Django 2.1.1 on 2018-09-15 06:30

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_contenttranslation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menutranslation',
            name='parent',
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Menu'),
        ),
    ]
