# Generated by Django 2.1.1 on 2018-09-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20180915_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menutranslation',
            old_name='link',
            new_name='slug',
        ),
    ]
