# Generated by Django 2.1.1 on 2018-09-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_auto_20180915_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('basic', 'Basic content'), ('event', 'Event content')], default='basic', max_length=60),
        ),
    ]
