# Generated by Django 2.1.1 on 2018-09-15 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_auto_20180915_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='YouTubeVideoAlbum',
        ),
        migrations.RenameModel(
            old_name='AlbumTranslation',
            new_name='YouTubeVideoAlbumTranslation',
        ),
        migrations.AlterModelOptions(
            name='youtubevideoalbumtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'you tube video album Translation'},
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='basic.YouTubeVideoAlbum'),
        ),
        migrations.AlterModelTable(
            name='youtubevideoalbumtranslation',
            table='basic_youtubevideoalbum_translation',
        ),
    ]
