# Generated by Django 2.1.1 on 2018-09-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_auto_20180915_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideotranslation',
            name='url',
            field=models.CharField(help_text='https://www.youtube.com/watch?v=jsQgF1693vo', max_length=60, null=True),
        ),
    ]
