# Generated by Django 2.1.1 on 2018-09-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_auto_20180915_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('basic', 'Basic content'), ('event', 'Event content'), ('interesting', 'Interesting content')], default='basic', max_length=60),
        ),
    ]
