# Generated by Django 2.1.1 on 2018-09-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0018_auto_20180916_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='library/images/'),
        ),
    ]
