# Generated by Django 2.1.1 on 2018-09-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0021_auto_20180916_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='basic.Library'),
        ),
    ]
