# Generated by Django 2.1.1 on 2018-09-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0025_auto_20180918_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
