# Generated by Django 2.1.1 on 2018-09-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0026_review_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideoalbum',
            name='video_type',
            field=models.CharField(choices=[('personal', 'Personal videos'), ('audio', 'Audio materials'), ('video', 'Video materials')], default='personal', max_length=60),
        ),
    ]
